f = 'SSRHA'
an = '16'
table = 'ssrha'
champ = 'ssr'

library(dplyr)
# SSR

rm(list = ls())
imp <- function(f, champ, table, an){
  temp <- readxl::read_excel(paste0('formats/excel/Formats ', f,' ',an, '.xlsx'))
  temp %>% mutate(champ = champ, table = table, an = an)
}

bind_rows(
  # SSRHA
  imp('SSRHA', 'ssr', 'ssrha', '11'),
  imp('SSRHA', 'ssr', 'ssrha', '12'),
  imp('SSRHA', 'ssr', 'ssrha', '13'),
  imp('SSRHA', 'ssr', 'ssrha', '14'),
  imp('SSRHA', 'ssr', 'ssrha', '15'),
  imp('SSRHA', 'ssr', 'ssrha', '16'),
  imp('SSRHA', 'ssr', 'ssrha', '17'),
  imp('SSRHA', 'ssr', 'ssrha', '18'),
  imp('SSRHA', 'ssr', 'ssrha', '19'),
  imp('SSRHA', 'ssr', 'ssrha', '20'),
  imp('SSRHA', 'ssr', 'ssrha', '21'),
  imp('SSRHA', 'ssr', 'ssrha', '22'),
  
  # RHA
  imp('RHA', 'ssr', 'rha', '11'),
  imp('RHA', 'ssr', 'rha', '12'),
  imp('RHA', 'ssr', 'rha', '13'),
  imp('RHA', 'ssr', 'rha', '14'),
  imp('RHA', 'ssr', 'rha', '15'),
  imp('RHA', 'ssr', 'rha', '16'),
  imp('RHA', 'ssr', 'rha', '17'),
  imp('RHA', 'ssr', 'rha', '18'),
  imp('RHA', 'ssr', 'rha', '19'),
  imp('RHA', 'ssr', 'rha', '20'),
  imp('RHA', 'ssr', 'rha', '21'),
  imp('RHA', 'ssr', 'rha', '22'),
  
  # RHS
  imp('RHS', 'ssr', 'rhs', '11'),
  imp('RHS', 'ssr', 'rhs', '12'),
  imp('RHS', 'ssr', 'rhs', '13'),
  imp('RHS', 'ssr', 'rhs', '14'),
  imp('RHS', 'ssr', 'rhs', '15'),
  imp('RHS', 'ssr', 'rhs', '16'),
  imp('RHS', 'ssr', 'rhs', '17'),
  imp('RHS', 'ssr', 'rhs', '18'),
  imp('RHS', 'ssr', 'rhs', '19'),
  imp('RHS', 'ssr', 'rhs', '20'),
  imp('RHS', 'ssr', 'rhs', '21'),
  imp('RHS', 'ssr', 'rhs', '22'),
  
  # RPS
  imp('RPS', 'psy', 'rps', '22'),
  imp('RPS', 'psy', 'rps', '21'),
  imp('RPS', 'psy', 'rps', '20'),
  imp('RPS', 'psy', 'rps', '19'),
  imp('RPS', 'psy', 'rps', '18'),
  imp('RPS', 'psy', 'rps', '17'),
  imp('RPS', 'psy', 'rps', '16'),
  imp('RPS', 'psy', 'rps', '15'),
  imp('RPS', 'psy', 'rps', '14'),
  imp('RPS', 'psy', 'rps', '13'),
  imp('RPS', 'psy', 'rps', '12'),
  imp('RPS', 'psy', 'rps', '11'),
  
  # RAA
  imp('RAA', 'psy', 'raa', '22'),
  imp('RAA', 'psy', 'raa', '21'),
  imp('RAA', 'psy', 'raa', '20'),
  imp('RAA', 'psy', 'raa', '19'),
  imp('RAA', 'psy', 'raa', '18'),
  imp('RAA', 'psy', 'raa', '17'),
  imp('RAA', 'psy', 'raa', '16'),
  imp('RAA', 'psy', 'raa', '15'),
  imp('RAA', 'psy', 'raa', '14'),
  imp('RAA', 'psy', 'raa', '13'),
  imp('RAA', 'psy', 'raa', '12'),
  imp('RAA', 'psy', 'raa', '11'),
  
  # RHA ANO
  imp('RHA ANO', 'ssr', 'rha_ano', '11'),
  imp('RHA ANO', 'ssr', 'rha_ano', '12'),
  imp('RHA ANO', 'ssr', 'rha_ano', '13'),
  imp('RHA ANO', 'ssr', 'rha_ano', '14'),
  imp('RHA ANO', 'ssr', 'rha_ano', '15'),
  imp('RHA ANO', 'ssr', 'rha_ano', '16'),
  imp('RHA ANO', 'ssr', 'rha_ano', '17'),
  imp('RHA ANO', 'ssr', 'rha_ano', '18'),
  imp('RHA ANO', 'ssr', 'rha_ano', '19'),
  imp('RHA ANO', 'ssr', 'rha_ano', '20'),
  imp('RHA ANO', 'ssr', 'rha_ano', '21'),
  imp('RHA ANO', 'ssr', 'rha_ano', '22'),
  
  # RHA MED
  imp('RHA MED', 'ssr', 'rha_med', '11'),
  imp('RHA MED', 'ssr', 'rha_med', '12'),
  imp('RHA MED', 'ssr', 'rha_med', '13'),
  imp('RHA MED', 'ssr', 'rha_med', '14'),
  imp('RHA MED', 'ssr', 'rha_med', '15'),
  imp('RHA MED', 'ssr', 'rha_med', '16'),
  imp('RHA MED', 'ssr', 'rha_med', '17'),
  imp('RHA MED', 'ssr', 'rha_med', '18'),
  imp('RHA MED', 'ssr', 'rha_med', '19'),
  imp('RHA MED', 'ssr', 'rha_med', '20'),
  imp('RHA MED', 'ssr', 'rha_med', '21'),
  imp('RHA MED', 'ssr', 'rha_med', '22'),
  
  # imp('RHA UM', 'ssr', 'rha_um', '11'),
  # imp('RHA UM', 'ssr', 'rha_um', '12'),
  imp('RHA UM', 'ssr', 'rha_um', '13'),
  imp('RHA UM', 'ssr', 'rha_um', '14'),
  imp('RHA UM', 'ssr', 'rha_um', '15'),
  imp('RHA UM', 'ssr', 'rha_um', '16'),
  imp('RHA UM', 'ssr', 'rha_um', '17'),
  imp('RHA UM', 'ssr', 'rha_um', '18'),
  imp('RHA UM', 'ssr', 'rha_um', '19'),
  imp('RHA UM', 'ssr', 'rha_um', '20'),
  imp('RHA UM', 'ssr', 'rha_um', '21'),
  imp('RHA UM', 'ssr', 'rha_um', '22'),
  
  # RAPSS
  imp('RAPSS', 'had', 'rapss', '11'),
  imp('RAPSS', 'had', 'rapss', '12'),
  imp('RAPSS', 'had', 'rapss', '13'),
  imp('RAPSS', 'had', 'rapss', '14'),
  imp('RAPSS', 'had', 'rapss', '15'),
  imp('RAPSS', 'had', 'rapss', '16'),
  imp('RAPSS', 'had', 'rapss', '17'),
  imp('RAPSS', 'had', 'rapss', '18'),
  imp('RAPSS', 'had', 'rapss', '19'),
  imp('RAPSS', 'had', 'rapss', '20'),
  imp('RAPSS', 'had', 'rapss', '20_H33'),
  imp('RAPSS', 'had', 'rapss', '21'),
  imp('RAPSS', 'had', 'rapss', '22'),
  
  # RAPSS ANO
  imp('RAPSS ANO', 'had', 'rapss_ano', '11'),
  imp('RAPSS ANO', 'had', 'rapss_ano', '12'),
  imp('RAPSS ANO', 'had', 'rapss_ano', '13'),
  imp('RAPSS ANO', 'had', 'rapss_ano', '14'),
  imp('RAPSS ANO', 'had', 'rapss_ano', '15'),
  imp('RAPSS ANO', 'had', 'rapss_ano', '16'),
  imp('RAPSS ANO', 'had', 'rapss_ano', '17'),
  imp('RAPSS ANO', 'had', 'rapss_ano', '18'),
  imp('RAPSS ANO', 'had', 'rapss_ano', '19'),
  imp('RAPSS ANO', 'had', 'rapss_ano', '20'),
  imp('RAPSS ANO', 'had', 'rapss_ano', '20_H33'),
  imp('RAPSS ANO', 'had', 'rapss_ano', '21'),
  imp('RAPSS ANO', 'had', 'rapss_ano', '22'),
  
  # RAPSS MED
  imp('RAPSS MED', 'had', 'rapss_med', '11'),
  imp('RAPSS MED', 'had', 'rapss_med', '12'),
  imp('RAPSS MED', 'had', 'rapss_med', '13'),
  imp('RAPSS MED', 'had', 'rapss_med', '14'),
  imp('RAPSS MED', 'had', 'rapss_med', '15'),
  imp('RAPSS MED', 'had', 'rapss_med', '16'),
  imp('RAPSS MED', 'had', 'rapss_med', '17'),
  imp('RAPSS MED', 'had', 'rapss_med', '18'),
  imp('RAPSS MED', 'had', 'rapss_med', '19'),
  imp('RAPSS MED', 'had', 'rapss_med', '20'),
  imp('RAPSS MED', 'had', 'rapss_med', '21'),
  imp('RAPSS MED', 'had', 'rapss_med', '22'),
  
  # RPSA
  imp('RPSA', 'psy', 'rpsa', '12'),
  imp('RPSA', 'psy', 'rpsa', '13'),
  imp('RPSA', 'psy', 'rpsa', '14'),
  imp('RPSA', 'psy', 'rpsa', '15'),
  imp('RPSA', 'psy', 'rpsa', '16'),
  imp('RPSA', 'psy', 'rpsa', '17'),
  imp('RPSA', 'psy', 'rpsa', '18'),
  imp('RPSA', 'psy', 'rpsa', '19'),
  imp('RPSA', 'psy', 'rpsa', '20'),
  imp('RPSA', 'psy', 'rpsa', '21'),
  imp('RPSA', 'psy', 'rpsa', '22'),
  
  # RPSA ANO
  imp('RPSA ANO', 'psy', 'rpsa_ano', '12'),
  imp('RPSA ANO', 'psy', 'rpsa_ano', '13'),
  imp('RPSA ANO', 'psy', 'rpsa_ano', '14'),
  imp('RPSA ANO', 'psy', 'rpsa_ano', '15'),
  imp('RPSA ANO', 'psy', 'rpsa_ano', '16'),
  imp('RPSA ANO', 'psy', 'rpsa_ano', '17'),
  imp('RPSA ANO', 'psy', 'rpsa_ano', '18'),
  imp('RPSA ANO', 'psy', 'rpsa_ano', '19'),
  imp('RPSA ANO', 'psy', 'rpsa_ano', '20'),
  imp('RPSA ANO', 'psy', 'rpsa_ano', '21'),
  imp('RPSA ANO', 'psy', 'rpsa_ano', '22'),
  
  # R3A
  imp('R3A', 'psy', 'r3a', '12'),
  imp('R3A', 'psy', 'r3a', '13'),
  imp('R3A', 'psy', 'r3a', '14'),
  imp('R3A', 'psy', 'r3a', '15'),
  imp('R3A', 'psy', 'r3a', '16'),
  imp('R3A', 'psy', 'r3a', '17'),
  imp('R3A', 'psy', 'r3a', '18'),
  imp('R3A', 'psy', 'r3a', '19'),
  imp('R3A', 'psy', 'r3a', '20'),
  imp('R3A', 'psy', 'r3a', '21'),
  imp('R3A', 'psy', 'r3a', '22'),
  
  # RSA
  imp('RSA', 'mco', 'rsa', '11'),
  imp('RSA', 'mco', 'rsa', '12'),
  imp('RSA', 'mco', 'rsa', '13'),
  imp('RSA', 'mco', 'rsa', '14'),
  imp('RSA', 'mco', 'rsa', '15'),
  imp('RSA', 'mco', 'rsa', '16'),
  imp('RSA', 'mco', 'rsa', '17'),
  imp('RSA', 'mco', 'rsa', '18'),
  imp('RSA', 'mco', 'rsa', '19'),
  imp('RSA', 'mco', 'rsa', '20'),
  imp('RSA', 'mco', 'rsa', '21'),
  imp('RSA', 'mco', 'rsa', '22'),
  
  # RSA ACTES
  imp('RSA ACTES', 'mco', 'rsa_actes', '11'),
  imp('RSA ACTES', 'mco', 'rsa_actes', '12'),
  imp('RSA ACTES', 'mco', 'rsa_actes', '13'),
  imp('RSA ACTES', 'mco', 'rsa_actes', '14'),
  imp('RSA ACTES', 'mco', 'rsa_actes', '15'),
  imp('RSA ACTES', 'mco', 'rsa_actes', '16'),
  imp('RSA ACTES', 'mco', 'rsa_actes', '17'),
  imp('RSA ACTES', 'mco', 'rsa_actes', '18'),
  imp('RSA ACTES', 'mco', 'rsa_actes', '19'),
  imp('RSA ACTES', 'mco', 'rsa_actes', '20'),
  imp('RSA ACTES', 'mco', 'rsa_actes', '21'),
  imp('RSA ACTES', 'mco', 'rsa_actes', '22'),
  
  # RSA UM
   imp('RSA UM', 'mco', 'rsa_um', '11'),
   imp('RSA UM', 'mco', 'rsa_um', '12'),
   imp('RSA UM', 'mco', 'rsa_um', '13'),
   imp('RSA UM', 'mco', 'rsa_um', '14'),
   imp('RSA UM', 'mco', 'rsa_um', '15'),
   imp('RSA UM', 'mco', 'rsa_um', '16'),
   imp('RSA UM', 'mco', 'rsa_um', '17'),
   imp('RSA UM', 'mco', 'rsa_um', '18'),
   imp('RSA UM', 'mco', 'rsa_um', '19'),
   imp('RSA UM', 'mco', 'rsa_um', '20'),
   imp('RSA UM', 'mco', 'rsa_um', '21'),
   imp('RSA UM', 'mco', 'rsa_um', '22'),
  
  # RSA ANO
  imp('RSA ANO', 'mco', 'rsa_ano', '11'),
  imp('RSA ANO', 'mco', 'rsa_ano', '12'),
  imp('RSA ANO', 'mco', 'rsa_ano', '13'),
  imp('RSA ANO', 'mco', 'rsa_ano', '14'),
  imp('RSA ANO', 'mco', 'rsa_ano', '15'),
  imp('RSA ANO', 'mco', 'rsa_ano', '16'),
  imp('RSA ANO', 'mco', 'rsa_ano', '17'),
  imp('RSA ANO', 'mco', 'rsa_ano', '18'),
  imp('RSA ANO', 'mco', 'rsa_ano', '19'),
  imp('RSA ANO', 'mco', 'rsa_ano', '20'),
  imp('RSA ANO', 'mco', 'rsa_ano', '21'),
  imp('RSA ANO', 'mco', 'rsa_ano', '22'),
  
  # RSA MED
  imp('RSA MED', 'mco', 'rsa_med', '11'),
  imp('RSA MED', 'mco', 'rsa_med', '12'),
  imp('RSA MED', 'mco', 'rsa_med', '13'),
  imp('RSA MED', 'mco', 'rsa_med', '14'),
  imp('RSA MED', 'mco', 'rsa_med', '15'),
  imp('RSA MED', 'mco', 'rsa_med', '16'),
  imp('RSA MED', 'mco', 'rsa_med', '17'),
  imp('RSA MED', 'mco', 'rsa_med', '18'),
  imp('RSA MED', 'mco', 'rsa_med', '19'),
  imp('RSA MED', 'mco', 'rsa_med', '20'),
  imp('RSA MED', 'mco', 'rsa_med', '21'),
  imp('RSA MED', 'mco', 'rsa_med', '22'),
  
  # RSA DMI
  imp('RSA DMI', 'mco', 'rsa_dmi', '11'),
  imp('RSA DMI', 'mco', 'rsa_dmi', '12'),
  imp('RSA DMI', 'mco', 'rsa_dmi', '13'),
  imp('RSA DMI', 'mco', 'rsa_dmi', '14'),
  imp('RSA DMI', 'mco', 'rsa_dmi', '15'),
  imp('RSA DMI', 'mco', 'rsa_dmi', '16'),
  imp('RSA DMI', 'mco', 'rsa_dmi', '17'),
  imp('RSA DMI', 'mco', 'rsa_dmi', '18'),
  imp('RSA DMI', 'mco', 'rsa_dmi', '19'),
  imp('RSA DMI', 'mco', 'rsa_dmi', '20'),
  imp('RSA DMI', 'mco', 'rsa_dmi', '21'),
  imp('RSA DMI', 'mco', 'rsa_dmi', '22'),
  
  # RSA IVG
  imp('RSA IVG', 'mco', 'rsa_ivg', '17'),
  imp('RSA IVG', 'mco', 'rsa_ivg', '18'),
  imp('RSA IVG', 'mco', 'rsa_ivg', '19'),
  imp('RSA IVG', 'mco', 'rsa_ivg', '20'),
  imp('RSA IVG', 'mco', 'rsa_ivg', '21'),
  
  # RSA TPT
  imp('RSA TPT', 'mco', 'rsa_tpt', '21'),
  imp('RSA TPT', 'mco', 'rsa_tpt', '22'),
  
  # RSA DIAP
  imp('RSA DIAP', 'mco', 'rsa_diap', '11'),
  imp('RSA DIAP', 'mco', 'rsa_diap', '12'),
  imp('RSA DIAP', 'mco', 'rsa_diap', '13'),
  imp('RSA DIAP', 'mco', 'rsa_diap', '14'),
  imp('RSA DIAP', 'mco', 'rsa_diap', '15'),
  imp('RSA DIAP', 'mco', 'rsa_diap', '16'),
  imp('RSA DIAP', 'mco', 'rsa_diap', '17'),
  imp('RSA DIAP', 'mco', 'rsa_diap', '18'),
  imp('RSA DIAP', 'mco', 'rsa_diap', '19'),
  imp('RSA DIAP', 'mco', 'rsa_diap', '20'),
  imp('RSA DIAP', 'mco', 'rsa_diap', '21'),
  imp('RSA DIAP', 'mco', 'rsa_diap', '22'),
  
  # RSA PIE
  imp('RSA PIE', 'mco', 'rsa_pie', '11'),
  imp('RSA PIE', 'mco', 'rsa_pie', '12'),
  imp('RSA PIE', 'mco', 'rsa_pie', '13'),
  imp('RSA PIE', 'mco', 'rsa_pie', '14'),
  imp('RSA PIE', 'mco', 'rsa_pie', '15'),
  imp('RSA PIE', 'mco', 'rsa_pie', '16'),
  imp('RSA PIE', 'mco', 'rsa_pie', '17'),
  imp('RSA PIE', 'mco', 'rsa_pie', '18'),
  imp('RSA PIE', 'mco', 'rsa_pie', '19'),
  imp('RSA PIE', 'mco', 'rsa_pie', '20'),
  imp('RSA PIE', 'mco', 'rsa_pie', '21'),
  imp('RSA PIE', 'mco', 'rsa_pie', '22'),
  
  # RSA PO
  imp('RSA PO', 'mco', 'rsa_po', '11'),
  imp('RSA PO', 'mco', 'rsa_po', '12'),
  imp('RSA PO', 'mco', 'rsa_po', '13'),
  imp('RSA PO', 'mco', 'rsa_po', '14'),
  imp('RSA PO', 'mco', 'rsa_po', '15'),
  imp('RSA PO', 'mco', 'rsa_po', '16'),
  imp('RSA PO', 'mco', 'rsa_po', '17'),
  imp('RSA PO', 'mco', 'rsa_po', '18'),
  imp('RSA PO', 'mco', 'rsa_po', '19'),
  imp('RSA PO', 'mco', 'rsa_po', '20'),
  imp('RSA PO', 'mco', 'rsa_po', '21'),
  imp('RSA PO', 'mco', 'rsa_po', '22'),
  
  # RUM
  imp('RUM', 'mco', 'rum', '11'),
  imp('RUM', 'mco', 'rum', '12'),
  imp('RUM', 'mco', 'rum', '13'),
  imp('RUM', 'mco', 'rum', '14'),
  imp('RUM', 'mco', 'rum', '15'),
  imp('RUM', 'mco', 'rum', '16'),
  imp('RUM', 'mco', 'rum', '17'),
  imp('RUM', 'mco', 'rum', '18'),
  imp('RUM', 'mco', 'rum', '19'),
  imp('RUM', 'mco', 'rum', '20'),
  imp('RUM', 'mco', 'rum', '21'),
  imp('RUM', 'mco', 'rum', '22'),
  
  # RUM
  imp('RUM ACTES', 'mco', 'rum_actes', '11'),
  imp('RUM ACTES', 'mco', 'rum_actes', '12'),
  imp('RUM ACTES', 'mco', 'rum_actes', '13'),
  imp('RUM ACTES', 'mco', 'rum_actes', '14'),
  imp('RUM ACTES', 'mco', 'rum_actes', '15_116'),
  imp('RUM ACTES', 'mco', 'rum_actes', '15_117'),
  imp('RUM ACTES', 'mco', 'rum_actes', '16'),
  imp('RUM ACTES', 'mco', 'rum_actes', '17'),
  imp('RUM ACTES', 'mco', 'rum_actes', '18'),
  imp('RUM ACTES', 'mco', 'rum_actes', '19'),
  imp('RUM ACTES', 'mco', 'rum_actes', '20'),
  imp('RUM ACTES', 'mco', 'rum_actes', '21'),
  imp('RUM ACTES', 'mco', 'rum_actes', '22'),
  
  # RUM ANO
  imp('RUM ANO', 'mco', 'rum_ano', '11'),
  imp('RUM ANO', 'mco', 'rum_ano', '12'),
  imp('RUM ANO', 'mco', 'rum_ano', '13'),
  imp('RUM ANO', 'mco', 'rum_ano', '14'),
  imp('RUM ANO', 'mco', 'rum_ano', '15'),
  imp('RUM ANO', 'mco', 'rum_ano', '16'),
  imp('RUM ANO', 'mco', 'rum_ano', '17'),
  imp('RUM ANO', 'mco', 'rum_ano', '18'),
  imp('RUM ANO', 'mco', 'rum_ano', '19'),
  imp('RUM ANO', 'mco', 'rum_ano', '20'),
  imp('RUM ANO', 'mco', 'rum_ano', '21'),
  imp('RUM ANO', 'mco', 'rum_ano', '22'),
  
  # RPSS ANO
  imp('RPSS ANO', 'had', 'rpss_ano', '22'),
  imp('RPSS ANO', 'had', 'rpss_ano', '21'),
  imp('RPSS ANO', 'had', 'rpss_ano', '20'),
  imp('RPSS ANO', 'had', 'rpss_ano', '19'),
  imp('RPSS ANO', 'had', 'rpss_ano', '18'),
  imp('RPSS ANO', 'had', 'rpss_ano', '17'),
  imp('RPSS ANO', 'had', 'rpss_ano', '16'),
  imp('RPSS ANO', 'had', 'rpss_ano', '15'),
  imp('RPSS ANO', 'had', 'rpss_ano', '14'),
  imp('RPSS ANO', 'had', 'rpss_ano', '13'),
  imp('RPSS ANO', 'had', 'rpss_ano', '12'),
  imp('RPSS ANO', 'had', 'rpss_ano', '11'),
  
  # RHS ANO
  imp('RHS ANO', 'ssr', 'rhs_ano', '22'),
  imp('RHS ANO', 'ssr', 'rhs_ano', '21'),
  imp('RHS ANO', 'ssr', 'rhs_ano', '20'),
  imp('RHS ANO', 'ssr', 'rhs_ano', '19'),
  imp('RHS ANO', 'ssr', 'rhs_ano', '18'),
  imp('RHS ANO', 'ssr', 'rhs_ano', '17'),
  imp('RHS ANO', 'ssr', 'rhs_ano', '16'),
  imp('RHS ANO', 'ssr', 'rhs_ano', '15'),
  imp('RHS ANO', 'ssr', 'rhs_ano', '14'),
  imp('RHS ANO', 'ssr', 'rhs_ano', '13'),
  imp('RHS ANO', 'ssr', 'rhs_ano', '12'),
  imp('RHS ANO', 'ssr', 'rhs_ano', '11'),
  
  # RPS ANO
  imp('RPS ANO', 'psy', 'rps_ano', '22'),
  imp('RPS ANO', 'psy', 'rps_ano', '21'),
  imp('RPS ANO', 'psy', 'rps_ano', '20'),
  imp('RPS ANO', 'psy', 'rps_ano', '19'),
  imp('RPS ANO', 'psy', 'rps_ano', '18'),
  imp('RPS ANO', 'psy', 'rps_ano', '17'),
  imp('RPS ANO', 'psy', 'rps_ano', '16'),
  imp('RPS ANO', 'psy', 'rps_ano', '15'),
  imp('RPS ANO', 'psy', 'rps_ano', '14'),
  imp('RPS ANO', 'psy', 'rps_ano', '13'),
  imp('RPS ANO', 'psy', 'rps_ano', '12'),
  imp('RPS ANO', 'psy', 'rps_ano', '11'),
  
  # RUM MED
  imp('RUM MED', 'mco', 'rum_med', '11'),
  imp('RUM MED', 'mco', 'rum_med', '12'),
  imp('RUM MED', 'mco', 'rum_med', '13'),
  imp('RUM MED', 'mco', 'rum_med', '14'),
  imp('RUM MED', 'mco', 'rum_med', '15'),
  imp('RUM MED', 'mco', 'rum_med', '16'),
  imp('RUM MED', 'mco', 'rum_med', '17'),
  imp('RUM MED', 'mco', 'rum_med', '18'),
  imp('RUM MED', 'mco', 'rum_med', '19'),
  imp('RUM MED', 'mco', 'rum_med', '20'),
  imp('RUM MED', 'mco', 'rum_med', '21'),
  imp('RUM MED', 'mco', 'rum_med', '22'),
  
  # RUM DMI
  imp('RUM DMI', 'mco', 'rum_dmi', '11'),
  imp('RUM DMI', 'mco', 'rum_dmi', '12'),
  imp('RUM DMI', 'mco', 'rum_dmi', '13'),
  imp('RUM DMI', 'mco', 'rum_dmi', '14'),
  imp('RUM DMI', 'mco', 'rum_dmi', '15'),
  imp('RUM DMI', 'mco', 'rum_dmi', '16'),
  imp('RUM DMI', 'mco', 'rum_dmi', '17'),
  imp('RUM DMI', 'mco', 'rum_dmi', '18'),
  imp('RUM DMI', 'mco', 'rum_dmi', '19'),
  imp('RUM DMI', 'mco', 'rum_dmi', '20'),
  imp('RUM DMI', 'mco', 'rum_dmi', '21'),
  imp('RUM DMI', 'mco', 'rum_dmi', '22'),
  
  # RUM FICHCOMP IVG
  imp('RUM IVG', 'mco', 'rum_ivg', '17'),
  imp('RUM IVG', 'mco', 'rum_ivg', '18'),
  imp('RUM IVG', 'mco', 'rum_ivg', '19'),
  imp('RUM IVG', 'mco', 'rum_ivg', '20'),
  imp('RUM IVG', 'mco', 'rum_ivg', '21'),
  imp('RUM IVG', 'mco', 'rum_ivg', '22'),
  
  imp('RUM TPT', 'mco', 'rum_tpt', '21'),
  imp('RUM TPT', 'mco', 'rum_tpt', '22'),
  
  # Fichcomp po
  imp('RUM FICHCOMP', 'mco', 'ffc_in', '11'),
  imp('RUM FICHCOMP', 'mco', 'ffc_in', '12'),
  imp('RUM FICHCOMP', 'mco', 'ffc_in', '13'),
  imp('RUM FICHCOMP', 'mco', 'ffc_in', '14'),
  imp('RUM FICHCOMP', 'mco', 'ffc_in', '15'),
  imp('RUM FICHCOMP', 'mco', 'ffc_in', '16'),
  imp('RUM FICHCOMP', 'mco', 'ffc_in', '17'),
  imp('RUM FICHCOMP', 'mco', 'ffc_in', '18'),
  imp('RUM FICHCOMP', 'mco', 'ffc_in', '19'),
  imp('RUM FICHCOMP', 'mco', 'ffc_in', '20'),
  imp('RUM FICHCOMP', 'mco', 'ffc_in', '21'),
  imp('RUM FICHCOMP', 'mco', 'ffc_in', '22'),
  
  # UM
  imp('UM', 'mco', 'um', '11'),
  imp('UM', 'mco', 'um', '12'),
  imp('UM', 'mco', 'um', '13'),
  imp('UM', 'mco', 'um', '14'),
  imp('UM', 'mco', 'um', '15'),
  imp('UM', 'mco', 'um', '16'),
  imp('UM', 'mco', 'um', '17'),
  imp('UM', 'mco', 'um', '18'),
  imp('UM', 'mco', 'um', '19'),
  imp('UM', 'mco', 'um', '20'),
  imp('UM', 'mco', 'um', '21'),
  imp('UM', 'mco', 'um', '22'),
  
  # TRA
  imp('TRA MCO', 'mco', 'tra', 'xx'),
  imp('TRA HAD', 'had', 'tra', 'xx'),
  imp('TRA SSR', 'ssr', 'tra', 'xx'),
  imp('TRA PSY_R3A', 'psy', 'psy_r3a', 'xx'),
  imp('TRA PSY_RPSA', 'psy', 'psy_rpsa', 'xx'),

  # RAFAEL
  imp('RAFAEL', 'rsf', 'rafael', '12'),
  imp('RAFAEL', 'rsf', 'rafael', '13'),
  imp('RAFAEL', 'rsf', 'rafael', '14'),
  imp('RAFAEL', 'rsf', 'rafael', '15'),
  imp('RAFAEL', 'rsf', 'rafael', '16'),
  imp('RAFAEL', 'rsf', 'rafael', '17'),
  imp('RAFAEL', 'rsf', 'rafael', '18'),
  imp('RAFAEL', 'rsf', 'rafael', '19'),
  imp('RAFAEL', 'rsf', 'rafael', '20'),
  imp('RAFAEL', 'rsf', 'rafael', '21'),
  imp('RAFAEL', 'rsf', 'rafael', '22'),
  
  imp('RSF', 'rsf', 'rsf', '19'),
  imp('RSF', 'rsf', 'rsf', '20'),
  imp('RSF', 'rsf', 'rsf', '21'),
  imp('RSF', 'rsf', 'rsf', '22'),
  
  imp('RAFAEL LAMDA', 'rsf', 'rafael-maj', '22'),
  imp('RAFAEL LAMDA', 'rsf', 'rafael-maj', '21'),
  imp('RAFAEL LAMDA', 'rsf', 'rafael-maj', '20'),
  imp('RAFAEL LAMDA', 'rsf', 'rafael-maj', '19'),
  imp('RAFAEL LAMDA', 'rsf', 'rafael-maj', '18'),
  imp('RAFAEL LAMDA', 'rsf', 'rafael-maj', '17'),
  imp('RAFAEL LAMDA', 'rsf', 'rafael-maj', '16'),
  imp('RAFAEL LAMDA', 'rsf', 'rafael-maj', '15'),
  imp('RAFAEL LAMDA', 'rsf', 'rafael-maj', '14'),
  #imp('RAFAEL LAMDA', 'rsf', 'rafael-maj', '13'),
  
  # RAFAEL ANO-ACE
  imp('RAFAEL ANO', 'rsf', 'rafael_ano', '12'),
  imp('RAFAEL ANO', 'rsf', 'rafael_ano', '13'),
  imp('RAFAEL ANO', 'rsf', 'rafael_ano', '14'),
  imp('RAFAEL ANO', 'rsf', 'rafael_ano', '15'),
  imp('RAFAEL ANO', 'rsf', 'rafael_ano', '16'),
  imp('RAFAEL ANO', 'rsf', 'rafael_ano', '17'),
  imp('RAFAEL ANO', 'rsf', 'rafael_ano', '18'),
  imp('RAFAEL ANO', 'rsf', 'rafael_ano', '19'),
  imp('RAFAEL ANO', 'rsf', 'rafael_ano', '20'),
  imp('RAFAEL ANO', 'rsf', 'rafael_ano', '21'),
  imp('RAFAEL ANO', 'rsf', 'rafael_ano', '22'),
  
  imp('RAFAEL LAMDA ANO', 'rsf', 'rafael_ano-maj', '22'),
  imp('RAFAEL LAMDA ANO', 'rsf', 'rafael_ano-maj', '21'),
  imp('RAFAEL LAMDA ANO', 'rsf', 'rafael_ano-maj', '20'),
  imp('RAFAEL LAMDA ANO', 'rsf', 'rafael_ano-maj', '19'),
  imp('RAFAEL LAMDA ANO', 'rsf', 'rafael_ano-maj', '18'),
  imp('RAFAEL LAMDA ANO', 'rsf', 'rafael_ano-maj', '17'),
  imp('RAFAEL LAMDA ANO', 'rsf', 'rafael_ano-maj', '16'),
  imp('RAFAEL LAMDA ANO', 'rsf', 'rafael_ano-maj', '15'),
  imp('RAFAEL LAMDA ANO', 'rsf', 'rafael_ano-maj', '14')

) %>% select(libelle, longueur, position, fin, type, nom, champ, table, an, cla, Typer) -> formats

rg <- readxl::read_excel(paste0('formats/regpexpr/rg_curseurs.xlsx'))
class(rg$an) <- "character"
#
dplyr::bind_rows(formats,rg) -> formats
rm(imp)
rm(rg)
rm(.Random.seed)

save.image("formats/table_r/formats.RData")

